panr/hugo-theme-hello-friend

- layouts/partials/head.html
This fixes an issue where the favicon URL would look in the wrong place for the favicon.
> Fix bug in favicon path

- layouts/partials/head.html
Same correction was already done for the favicon.png path
> Fix bug in apple touch icon path

- README.md
- exampleSite/config.toml
- layouts/_default/list.html
- layouts/_default/single.html
- layouts/partials/menu.html
- layouts/partials/pagination.html
This PR makes the "Older posts" and "Newer posts" buttons translatable and allows to have a basic config without any theme specific changes for translated texts which removes unnecessary bloat from the config
>  Make "Older/Newer posts" texts configurable and allow empty config file

- layouts/_default/list.html
- layouts/_default/single.html
closes #33 (Don't prepend `img/` on cover links)
`cover: ` links can be updated with
```sh
find ./content/ -type f -name '*.md' -exec sed -i 's~cover: ~cover: img/~g' {} \;
```
for `yml` syntax
> Removed `img/` prefix from cover page params

- layouts/_default/list.html
- layouts/_default/single.html
This is to improve the SEO of website by avoid 301 redirect on `tags` link. Let me know what you think @panr :pray:. See here: https://www.gotchseo.com/301-redirects/
> Append trailing '/' to avoid 301 redirection

- layouts/partials/head.html
Hugo `0.55.5` complains that the current rss logic is deprecated.
```
WARN 2019/05/12 21:22:25 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like:
{{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}.
```
This PR is based on the current docs and should cover both RSS and JSON (and more alternative output formats): https://gohugo.io/templates/rss/#reference-your-rss-feed-in-head
> Update RSS link in head

- layouts/_default/list.html
- layouts/_default/single.html
closes #57 (Bug: Using urlize in cover image URL's replaces uppercase characters with lowercase ones)
> Removed urlize from cover links

- README.md
- layouts/partials/head.html
- layouts/partials/prepended_head.html
The purpose for this additional partial hook is to allow custom link, script, or style tags to be inserted before the theme declares any of it's own. This is necessary in a scenario such as linking in a library like `tachyons.css` which sets some default low-specificity tag styles, which are intended to be overwritten by the default styles declared by the template, but since the specificity of both are equally low the template css must be declared afterwards in order to have the higher specificity.
> Added a prepended_head.html partial hook

- layouts/_default/terms.html
I took the term index from #84, changed from taxonomy slug to name in the list, and added it to `layouts/_default`. This provides terms index for taxonomies, without changing how terms pages (`/tags/tag` and `/categories/category`) are shown.
I really felt this theme needed a `/tags` page :) This is how it looks: https://uctrl.dev/tags/
> Add terms index

- layouts/_default/list.html
I think I found a small bug while playing around with date display in the layout files.
Potential Issue: If there is no `.Date` data in a post file, the date is not displayed in the 'single' layout format. However, it is still displayed in the 'list' layout format as the default date 'Jan 01, 0001'.
Am I correct in assuming this is a mistake?
Fix: I've encapsulated the post date display in a quick conditional check to see if there is `.Date` data in a post file. This way it will not display the default date (or any date) in the 'list' layout, which would be consistent with the 'single' layout.
It's a quick fix. I didn't notice any issues from it. Hope it helps! :)
> Bug Fix to prevent incorrect default Date display in List layout

- layouts/_default/single.html
Same as 95906d6 where you disabled pagination for non-posts, but for comments this time.
Generally speaking, I wouldn't think that you'd want comments to show on a project page or an about page, but it may be nice to add a front matter variable check like comments: "true" in case anyone wants to enable them on a specific page. Let me know what you think.
> PR - Add condition to show *comments* only in defined contentType pages

- layouts/_default/single.html
Don't know why this was an H2 element, but it should be an H1 for a few reasons.  Semantically it makes much more sense.  Also, search engines will be looking for an H1 element in order to understand what the page is about and rankings will depend on it.
> Post title should be an H1 element for semantic and search rankings.

- source/css/menu.css
Today, only the text inside **more** submenu are clickable.
Change it to make all li clickable.
> Make "more" submenu entire li clickable

- README.md
- layouts/_default/rss.xml
As discussed in #147, I have added these two options (copied from README update):
**A page's cover image now appears at the top of its feed display**. This image is set manually using the cover params. If unset, the RSS generator searches for the first image file in the page bundle whose name includes 'featured', 'cover', or 'thumbnail'.
**You can optionally display the full page content in your RSS feed** (default is Description or Summary data from Front Matter). Set `rssFullText = true` in your `config.toml` file to enable this option.
**RSS validated and ready to go!**
> RSS Enhancements

- layouts/partials/head.html
**Rationale**
The maximum-scale=1 attribute prevents low-vision users from magnifying the page in some browsers. This isn't applicable to browsers like Safari in iOS 10+, but it would still be ideal to accommodate the aforementioned users for other browsers. Also, this results in a Lighthouse score penalty for accessibility. Alternatively, we could increase maximum-scale to 5 or above if removing it results in a known UI/UX regression I haven't looked into.
**Some further reading**
* https://a11yproject.com/posts/never-use-maximum-scale/
* https://web.dev/meta-viewport
* https://www.w3.org/TR/WCAG21/#resize-text
> Remove maximum-scale=1 from viewport meta tag

- README.md
- layouts/_default/index.html
- layouts/_default/list.html
- layouts/_default/single.html
The current image alt text for a cover image defaults to the post title. This is not great a11y. An alt text should be a description of the image itself.
This update adds instruction and functionality to define a custom alt text description for a cover image, which falls back to the default of the post or page title.
> Added custom alt text functionality to post cover images

- layouts/_default/index.html
- layouts/_default/list.html
Fixes the display of .Summary by removing `markdownify` from it.
This should resolve #203 (and #127, #100).
> Fix .Summary

- layouts/_default/single.html
As things stand, having a global toc=true and front matter toc=false result in Table of contents being visible, which is unexpected. This patch fixes that.
> add the ability to disable table of contents per-page/post

- layouts/_default/index.html
- layouts/_default/list.html
- layouts/_default/single.html
When using multiple languages the tags links on the blogposts header use always the main language base URL (even when you're on a post on other language). This PR fixes that
> Fix tags links in multilingual

- assets/css/main.css
Hugo gist shortcodes make use of GitHub Gist embedding. As the gist uses a table, it renders wrongly due to the global addressing in the general theme's css. This is a non-elegant fix, but solves the issue.
> Fix gist rendering

- layouts/_default/index.html
- layouts/_default/list.html
- layouts/_default/single.html
- layouts/partials/postcover.html
The post cover code is duplicated on `index`, `list` and `single`. Instead use a partial.
This will make it easier for users to make their own post cover implementation, like i have :)
This change should not affect existing installations.
> Move post cover to partial

- assets/css/main.scss
Previously, `rem` was used, which sets the font-size irrespective of its surrounding context. Changing this to `em` makes it possible to e.g. use inline code in headings without rendering them much smaller than the surrounding font.
Can be seen in effect on https://mbrgm.de/blog/kotlin-filternotnull-in-typescript/
> Make inline code font size relative to parent
